# Schema for the configuration files of the User Online Status module.

user_online_status.settings:
  type: config_object
  label: 'User Online Status settings'
  mapping:
    seconds_to_absent:
      type: integer
      label: 'Seconds until user is displayed as absent'
    seconds_to_offline:
      type: integer
      label: 'Seconds until user is displayed as offline'
    css_classes_online:
      type: string
      label: 'Additional field CSS class when user online'
    css_classes_absent:
      type: string
      label: 'Additional field CSS class when user absent'
    css_classes_offline:
      type: string
      label: 'Additional field CSS class when user offline'
