oe_webtools_page_feedback.settings:
  type: config_object
  label: 'Webtools Page Feedback Form settings'
  mapping:
    enabled:
      type: boolean
      label: 'Enabled'
      description: 'Whether the Page Feedback Form is enabled or not.'
    feedback_form_id:
      type: integer
      label: 'Form ID'
      description: 'ID of the corresponding Feedback Form where submissions will be recorded.'
