rdf_skos_language_mapping.settings:
  type: config_object
  label: 'Keeps a mapping between Drupal language codes and the ones present in Skos concepts and concept schemes.'
  mapping:
    language_mapping:
      type: sequence
      label: 'Language mapping configuration'
      sequence:
        type: string
        label: 'The language codes, keyed by the Drupal language codes they map to.'
