rdf_skos.graphs:
  type: config_entity
  label: 'RDF SKOS graphs configuration'
  mapping:
    entity_types:
      type: sequence
      label: 'Entity type graphs'
      sequence:
        type: sequence
        label: 'Graphs per entity type'
        sequence:
          type: mapping
          label: 'Graph info'
          mapping:
            name:
              type: string
              label: "The graph name"
            uri:
              type: string
              label: "The graph URI"

entity_reference_selection.default:skos_concept:
  type: entity_reference_selection.default
  label: 'SKOS Concept handler settings'
  mapping:
    concept_schemes:
      type: entity_reference_selection.skos_concept.concept_schemes
    concept_subset:
      type: string
      label: 'The ID of the ConceptSubset plugin'
    field:
      type: mapping
      label: 'Field information'
      mapping:
        field_name:
          type: string
          label: 'The name of the field'
        entity_type:
          type: string
          label: 'The entity type the field is on'
        bundle:
          type: string
          label: 'The entity type bundle the field is on'
        concept_schemes:
          type: entity_reference_selection.skos_concept.concept_schemes

field.storage_settings.skos_concept_entity_reference:
  type: field.storage_settings.entity_reference

field.field_settings.skos_concept_entity_reference:
  type: field.field_settings.entity_reference

field.widget.settings.skos_concept_entity_reference_autocomplete:
  type: field.widget.settings.entity_reference_autocomplete

field.formatter.settings.skos_concept_entity_reference_label:
  type: mapping
  mapping:
    link:
      type: boolean
      label: 'Link to the entity'

entity_reference_selection.skos_concept.concept_schemes:
  type: sequence
  label: 'The concept schemes to filter by'
  sequence:
    type: string
    label: 'The Concept Scheme URI'

views.filter.skos_concept_reference_id:
  type: views.filter.many_to_one
  label: 'Skos concept reference ID'
  mapping:
    type:
      type: string
      label: 'Selection type'
    limit:
      type: boolean
      label: 'Limit to concept scheme'
    concept_scheme:
      type: string
      label: 'The concept scheme to limit by'
    value:
      type: sequence
      label: 'Values'
      sequence:
        type: string
        label: 'Value'

views.filter_value.skos_concept_reference_id:
  type: views.filter_value.in_operator

field.value.skos_concept_entity_reference:
  type: mapping
  label: 'Default value'
  mapping:
    target_id:
      type: string
      label: 'Value'

field.widget.settings.skos_concept_entity_reference_options_select:
  type: mapping
  label: 'SKOS Concept select list display format settings'
  mapping:
    sort:
      type: string
      label: 'Sort'
