field.formatter.settings.typed_link:
  type: mapping
  label: 'Link format settings'
  mapping:
    trim_length:
      type: integer
      label: 'Trim link text length'
    url_only:
      type: boolean
      label: 'URL only'
    url_plain:
      type: boolean
      label: 'Show URL as plain text'
    rel:
      type: string
      label: 'Add rel="nofollow" to links'
    target:
      type: string
      label: 'Open link in new window'

field.formatter.settings.typed_link_separate:
  type: field.formatter.settings.link
  label: 'Link format settings'

field.widget.settings.typed_link:
  type: mapping
  label: 'Link format settings'
  mapping:
    placeholder_url:
      type: string
      label: 'Placeholder for URL'
    placeholder_title:
      type: label
      label: 'Placeholder for link text'

field.storage_settings.typed_link:
  type: mapping
  label: 'Typed link settings'
  mapping:
    allowed_values:
      type: sequence
      label: 'Allowed values list'
      sequence:
        type: string
        label: 'Allowed value'
    allowed_values_function:
      type: string
      label: 'Allowed values function'

field.field_settings.typed_link:
  type: mapping
  label: 'Link settings'
  mapping:
    title:
      type: integer
      label: 'Allow link text'
    link_type:
      type: integer
      label: 'Allowed link type'

field.value.typed_link:
  type: mapping
  label: 'Default value'
  mapping:
    title:
      type: label
      label: 'Link text'
    url:
      type: string
      label: 'URL'
    asset_type:
      type: string
      label: 'Asset Type'
    options:
      type: mapping
      label: 'Link options'
      mapping:
        query:
          type: sequence
          label: 'URL query key value pairs'
          sequence:
            type: string
        fragment:
          type: string
          label: 'URL fragment'
        absolute:
          type: boolean
          label: 'Is this URL absolute'
        https:
          type: boolean
          label: 'If the URL should use a secure protocol'
        attributes:
          type: sequence
          label: 'Link attributes'
          sequence:
            type: string
