oe_webtools_analytics_rules.webtools_analytics_rule.*:
  type: config_entity
  label: 'Webtools Analytics rule'
  mapping:
    id:
      type: string
      label: ID
    section:
      type: label
      label: 'Section'
    match_on_site_default_language:
      type: boolean
      label: 'Match on path alias for site default language'
    regex:
      type: string
      label: Regex
    weight:
      type: integer
      label: 'Weight'
